- name: install fail2ban package
  become: yes
  apt: 
    name: fail2ban 
    state: latest
    update_cache: yes

- name: copy fail2ban local config
  become: yes
  copy: 
    src: jail.local 
    dest: /etc/fail2ban/fail2ban.local 
    owner: root 
    group: root 
    mode: 0644