- hosts: webservers
  become: yes
  vars:
    http_port: 80
    https_port: 443
  roles:
    - {role: 'apache2', tags: 'apache2'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'fail2ban', tags: 'fail2ban'}
    - {role: 'sysadmin', tags: 'sysadmin'}