name: "Tests"

on:
  push:
    branches:
      - master
      - develop
      - pipeline_sandbox
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Go
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "::set-env name=GOROOT::$HOME/gotip"
          echo "::add-path::$HOME/gotip/bin"

      - name: Run testing
        run: go test -v -count=1 -timeout 30m -p 1 ./test/unit/