name: "Terraform Provisioning"

on:
  pull_request:
    branches:
      - master
    paths:
      - ./modules/*

jobs:
  test:
      name: "Tests"
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Setup Go
          uses: actions/setup-go@v2

        - name: Run testing
          run: make build-and-test
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
 