name: "Tests"

on:
  push:
    branches:
      - master
      - develop
      - pipeline_sandbox
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘^1.13.1’

      - name: Run testing
        run: go test -v -count=1 -timeout 30m -p 1 ./test/unit/